[package]
name = "counter-contract"
version = "0.1.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]
edition = "2018"

[dependencies]
oasis-std = "0.1"

[lib]
crate-type = ["cdylib"]

[profile.release]
incremental = false
lto = true
opt-level = "z"
panic = "abort"
